version: "3"
services:
  go-api:
    image: raphaelpsouza/chatting-api:1.0
    tty: true
    volumes:
      - ./backend:/build
    depends_on:
      - redis
    networks:
      - backend
    hostname: chatting

  redis:
    image: redis:7.0-alpine
    volumes:
      - ./cache:/data
    networks:
      - backend

  nginx:
    image: raphaelpsouza/chatting-nginx:1.0
    depends_on:
      - go-api
    ports:
      - "4000:4000"
    networks:
      - backend

  web:
    image: raphaelpsouza/chatting-web:1.0
    environment:
      - REACT_APP_BASE_URL=localhost:4000
    depends_on:
      - go-api
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
