version: "3"
services:
  go-api:
    image: chat-backend:1.0
    tty: true
    volumes:
      - ./backend:/build
    depends_on:
      - redis
    networks:
      - backend
    hostname: chatting

  redis:
    image: redis:7.0-alpine
    volumes:
      - ./cache:/data
    networks:
      - backend

  nginx:
    image: chat-nginx:1.0
    depends_on:
      - go-api
    ports:
      - "4000:4000"
    networks:
      - backend

networks:
  backend: